name: Docker Image CI
permissions: write-all
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - src/**
      - pom.xml
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
      - src/**
      - pom.xml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image for multiple platforms
      run: |
        docker buildx create --use
        docker buildx build . \
          --file Dockerfile \
          --platform linux/amd64,linux/arm64 \
          --cache-from=type=gha \
          --cache-to=type=gha,mode=max \
          -t ghcr.io/toe-fur/spotibot:beta \
          --push
